#+LaTeX_CLASS: org-university3
#+OPTIONS: author:nil, toc:nil, title:nil
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usepackage{pifont}
#+LATEX_HEADER: \usepackage{pstricks, pst-node}
#+LaTeX_HEADER: \usemintedstyle{perldoc}
#+LaTeX_HEADER: \usepackage[section]{placeins}
#+BIND: org-export-latex-title-command ""
#+LATEX_HEADER: \renewcommand{\contentsname}{ÍNDICE}
#+LATEX_HEADER: \renewcommand{\chaptername}{C}
#+LATEX_HEADER: \newcommand{\hmwkLeft}{}
#+LATEX_HEADER: \newcommand{\hmwkCenter}{\hmwkClass}
#+LATEX_HEADER: \newcommand{\hmwkRight}{\hmwkTitle}
#+LATEX_HEADER: \newcommand{\hmwkTitle}{Proyecto DDSI}
#+LATEX_HEADER: \newcommand{\hmwkTitleExtended}{Sistema de Información para el registro y control de alimentos y dietas}
#+LATEX_HEADER: \newcommand{\hmwkClass}{Desarrollo De Sistemas de Información}
#+LATEX_HEADER: \newcommand{\hmwkClassInstructor}{}
#+LATEX_HEADER: \newcommand{\hmwkAuthorName}{}
#+LATEX_HEADER: \setmonofont[Scale=0.7]{Monaco}
#+LATEX_HEADER: \setmonofont[Scale=0.9]{FreeMono}
#+LaTeX_HEADER: \usepackage{paralist}
#+LaTeX_HEADER: \usepackage{slashbox}
#+LaTeX_HEADER: \let\itemize\compactitem
#+LaTeX_HEADER: \let\itemize\compactitem
#+LaTeX_HEADER: \renewcommand{\bibname}{Referencias}
#+LaTeX_HEADER: \renewcommand{\figurename}{Figura}
#+LaTeX_HEADER: \renewcommand{\tablename}{Tabla}

#+begin_LaTeX
  \title{
  \begin{center}
  \vspace*{-2.5cm}
  \begin{figure}[htb]
  \begin{center}
  \includegraphics[width=4cm]{/home/dabuti/University/ugr.jpg}
  \end{center}
  \end{figure}
  \end{center}
  \Huge{\textbf{Universidad de Granada}}\\
  \vspace{1cm}
  \Huge{\textbf{Grado en Ingeniería Informática}}\\
  \vspace{2cm}
  \hrule{}
  \vspace{0.3cm}
  \textbf{\hmwkClass}\\
  \vspace{0.3cm}
  \hrule{}
  \vspace{2cm}
  \textbf{\hmwkTitle}\\
  \vspace{1cm}
  \textbf{\hmwkTitleExtended}\\
  \vspace{1.5cm}
  \textbf{\small{Iris García de Sebastián}}\\
  \textbf{\small{David Santiago Carrión}}\\
  \vspace{0.1cm}
  }
#+end_LaTeX

\maketitle
\clearpage
\tableofcontents
\clearpage

* Descripción
  Se pretende implementar un sistema para registrar las comidas que se
  llevan a cabo a lo largo del día y gestionar los alimentos. Para
  ello se almacenarán los ingredientes que componen cada receta y su
  cantidad, además de información nutricional acerca de cada alimento
  y el lugar y precio donde lo adquirimos.


** Registro de alimentos
   Al introducir los productos adquiridos en un supermercado estos
   deben agruparse en categorías con un nivel de abstracción
   superior, considerados como ingredientes. Por ejemplo si el
   usuario compra una botella de aceite  de oliva 'Jucaso' en el
   supermercado 'Coviran' y otra botella de aceite de oliva 'Borges'
   en el supermercado Mercadona, ambos producto deben almacenarse en
   el sistema bajo el producto 'aceite de oliva'.

   De este modo cada producto que empleemos en la elaboración de
   nuestra alimentación diaria está descrito por:
   - *nombre del producto*: una serie de caracteres.
   - *energía*: un número que indica las kilocalorías que aporta por
     cada 100 gramos de producto.
   - *Descripción*: detalles y explicaciones acerca del alimento.

   Los alimentos los podemos adquirir en distintos establecimientos,
   lo cual nos lleva a guardar información relevante acerca de los
   mismos como:
   - *nombre del establecimiento*: una serie de caracteres.
   - *dirección*: caracteres alfanuméricos que nos ayudan a ubicar la tienda.
   - *teléfono*: caracteres numéricos.
   - *web*: dirección web del comercio.

   Tanto los datos de los alimentos como los de los supermercados
   podrán ser modificados.


   Cada vez que se hace una compra se registra información de los
   productos adquiridos:
   - *producto*: el producto comprado.
   - *establecimiento*: donde lo hemos comprado.
   - *comprador*: el usuario que ha realizado la compra.
   - *cantidad*: número de unidades adquiridas del producto.
   - *precio*: número que indica el coste total.
   - *fecha*: cuando se realizó la adquisición.

\newpage
** Registro de dietas
   Con todos los ingredientes adquirdos se pueden cocinar recetas. Las
   recetas se describen y se almacena en el sistema teniendo en cuenta
   los siguientes puntos:
   - *nombre*: una serie de caracteres.
   - *personas*: número de comensales a los que puede abastecer.
   - *ingredientes*: un conjunto formado por los alimentos necesarios.
   - *cantidad*: indica la proporción de cada ingrediente.
   - *tiempo*: minutos que nos puede costar cocinarlo.
   - *valor nutricional*: número total de calorías que aporta la
     receta.
   - *descripción*: documento que indica los pasos a seguir para
     realizar el plato.

   \vspace{0.2cm}
   A partir de las diferentes recetas se pueden crear listas
   personalizadas de las mismas, generando dietas. Las dietas son
   creadas por los usuarios y les pertenecen a ellos exclusivamente. A
   diferencia de las recetas estas no se comparten.

   Se guardarán los siguientes puntos:
   - *nombre de la dieta*: una serie de caracteres.
   - *recetas*: el conjunto de recetas asociado a la dieta.
   - *descripción*: información adicional sobre la dieta descrita.
   - *usuario*: identifica al propietario de la dieta.

   \vspace{0.2cm}
   Tanto las recetas como las dietas han de poder ser editadas,
   eliminando y agregando ingredientes o recetas según el caso.

   Dada una dieta en concreto, se listará la información general de la
   misma junto con sus recetas asociadas, permitiendo al usuario
   hacerse una idea de los platos que puede preparar.

   Cada vez que alguien realiza una receta se registra quien cocinó la
   comida, para llevar un control de la despensa:
   - *Usuario*: quien la ha cocinado.
   - *Receta*: que receta se ha cocinado.
   - *Fecha*: cuando se ha realizado la comida.

   \vspace{0.2cm}
   Los usuarios podrán ver los platos que han realizado y se les
   ofrecerá la opción de eliminar una comida registrada, para subsanar
   posibles errores de registro.

\newpage
** Registro de usuarios
   La base de usuarios estarán registrados, permitiéndoles realizar
   dietas específicas, comidas, compras o recetas. Sus datos serían:
   - *nombre*: una serie de caracteres.
   - *primer apellido*: caracteres alfabéticos.
   - *segundo apellido*:  una serie de caracteres.
   - *nick*: caracteres por los que quiere ser identificado.
   - *contraseña*: combinación necesaria para entrar al sistema.

   \vspace{0.2cm}
   Los usuarios anónimos tienen la opción de darse de alta en el
   sistema proporcionando los datos previamente expuestos. A partir de
   entonces podrán acceder a las distintas operaciones que ofrece el
   sistema, así como editar o eliminar su perfil.



** Información y estadísticas
   Los usuarios del sistema tienen acceso a información extraida de
   las acciones que han ido llevando a cabo con el uso cotidiano del
   sistema.

   De este modo podrán acceder a una lista con todos los alimentos que
   tienen disponibles actualmente en la despensa y a una lista de
   recetas que pueden ser cocinadas en vista de los ingredientes con
   los que cuenta y las dietas que ha creado.

   Cuando un usuario crea una dieta y asocia los platos que desea,
   podrá obtener el coste que le supondría adquirir los productos, en
   los distintos supermercados, para ejecutar todos los platos de
   dicha dieta.

   Por último, el usuario deberá poder obtener su gasto medio en
   euros, tanto el diario como desde el inicio del presente mes.

* Análisis de requisitos
** Requisitos de datos
*** RD1-Datos nuevo producto
    - *Nombre*: una cadena de hasta 20 caracteres no vacía.
    - *Calorías*: un número decimal positivo.
    - *Descripción*: una cadena de hasta 200 caracteres.
*** RD2-Datos producto:
    - *Identificador* de producto: un número entero.
    - *Nombre*: una cadena de hasta 20 caracteres no vacía.
    - *Calorías*: un número decimal positivo.
    - *Descripción*: una cadena de hasta 200 caracteres.

*** RD3-Datos producto modificado:
    - *Identificador* de producto: un número entero.
    - *Nombre*: una cadena de hasta 20 caracteres.
    - *Calorías*: un número decimal positivo.
    - *Descripción*: una cadena de hasta 200 caracteres.

*** RD4-Identificador comprador:
    - *Identificador* de usuario: un número entero.

*** RD5-Lista de productos comprados:
    - *Identificador* de producto: un número entero.
    - *Nombre*: una cadena de hasta 20 caracteres no vacía.
    - *Calorías*: un número decimal positivo.
    - *Descripción*: una cadena de hasta 200 caracteres.

*** RD6-Datos nuevo super:
    - *Nombre*:  una cadena de hasta 20 caracteres no vacía.
    - *Dirección*:  una cadena de hasta 30 caracteres no vacía.
    - *Teléfono*: una cadena de 9 caracteres numéricos.
    - *Página* web: una cadena de hasta 20 caracteres no vacía.

*** RD7-Datos super:
    - *Identificador* de super: un número entero.
    - *Nombre*:  una cadena de hasta 20 caracteres no vacía.
    - *Dirección*:  una cadena de hasta 30 caracteres.
    - *Teléfono*: una cadena de hasta 9 caracteres numéricos.
    - *Página web*: una cadena de hasta 20 caracteres.

*** RD8-Datos super modificado:
    - *Identificador de super*: un número entero.
    - *Nombre*:  una cadena de hasta 20 caracteres.
    - *Dirección*:  una cadena de hasta 30 caracteres.
    - *Teléfono*: una cadena de hasta 9 caracteres numéricos.
    - *Página web*: una cadena de hasta 20 caracteres.

*** RD9-Datos nueva compra:
    - *Identificador* de usuario: un número entero.

*** RD10-Datos compra:
    - *Identificador de compra*: un número entero.
    - *Identificador de usuario*: un número entero.
    - *Fecha*: tres conjuntos de enteros formados los dos primeros por conjuntos de dos cifras y el 		tercero por un conjunto de cuatro cifras, separados por barras ('/').

*** RD11-Datos nueva línea de compra:
    - *Identificador de compra*: un número entero.
    - *Identificador de producto*: un número entero.
    - *Identificador de super*: un número entero.
    - *Cantidad*: un número entero mayor que cero.
    - *Importe*: un número decimal mayor que cero.

*** RD12-Datos línea de compra:
    - *Identificador de compra*: un número entero.
    - *Identificador de producto*: un número entero.
    - *Identificador de super*: un número entero.
    - *Cantidad*: un número entero mayor que cero.
    - *Importe*: un número decimal mayor que cero.

*** RD13-Datos línea de compra a eliminar:
    - *Identificador de compra*: un número entero.
    - *Identificador de producto*: un número entero.
    - *Identificador de super*: un número entero.

*** RD14-Datos nueva dieta:
    - *Identificador de usuario*: un número entero.
    - *Nombre*: una cadena de hasta 20 caracteres no vacía.
    - *Descripción*: una cadena de hasta 200 caracteres.

*** RD15-Datos dieta:
    - *Identificador de dieta*: un número entero.
    - *Identificador de usuario*: un número entero.
    - *Nombre*: una cadena de hasta 20 caracteres no vacía.
    - *Descripción*: una cadena de hasta 200 caracteres.

*** RD16-Datos nueva receta de dieta:
    - *Identificador de dieta*: un número entero.
    - *Identificador de receta*: un número entero.

*** RD17-Datos receta de dieta:
    - *Identificador de dieta*: un número entero.
    - *Identificador de receta*: un número entero.

*** RD18-Datos receta de dieta a eliminar:
    - *Identificador de dieta*: un número entero.
    - *Identificador de receta*: un número entero.

*** RD19-Datos nueva receta:
    - *Nombre*: una cadena de hasta 20 caracteres no vacía.
    - *Personas*: un número entero.
    - *Tiempo*: un número entero.
    - *Descripción*: una cadena de hasta 200 caracteres.

*** RD20-Datos receta:
    - *Identificador de receta*: un número entero.
    - *Nombre*: una cadena de hasta 20 caracteres no vacía.
    - *Personas*: un número entero mayor que cero.
    - *Tiempo*: un número entero mayor que cero.
    - *Descripción*: una cadena de hasta 200 caracteres.

*** RD21-Datos nuevo producto de receta:
    - *Identificador de producto*: un número entero.
    - *Identificador de receta*: un número entero.
    - *Cantidad*: un número entero.

*** RD22-Datos producto de receta:
    - *Identificador de producto*: un número entero.
    - *Identificador de receta*: un número entero.
    - *Cantidad*: un número entero.

*** RD23-Datos producto de receta a eliminar:
    - *Identificador de producto*: un número entero.
    - *Identificador de receta*: un número entero.

*** RD24-Datos receta modificada:
    - *Identificador de receta*: un número entero.
    - *Nombre*: una cadena de hasta 20 caracteres.
    - *Personas*: un número entero.
    - *Tiempo*: un número entero.
    - *Descripción*: una cadena de hasta 200 caracteres.

*** RD25-Datos nuevo usuario:
    - *Nombre*: una cadena de hasta 20 caracteres no vacía.
    - *Primer apellido*: una cadena de hasta 20 caracteres.
    - *Segundo apellido*: una cadena de hasta 20 caracteres.
    - *Nombre de usuario*: una cadena de hasta 20 caracteres.
    - *Contraseña*: una cadena alfanumérica de hasta 20 elementos.

*** RD26-Datos usuario:
    - *Identificador de usuario*: un número entero.
    - *Nombre*: una cadena de hasta 20 caracteres no vacía.
    - *Primer apellido*: una cadena de hasta 20 caracteres.
    - *Segundo apellido*: una cadena de hasta 20 caracteres.
    - *Nombre de usuario*: una cadena de hasta 20 caracteres.
    - *Contraseña*: una cadena alfanumérica de hasta 20 elementos.

*** RD27-Datos usuario modificado:
    - *Identificador de usuario*: un número entero.
    - *Nombre*: una cadena de hasta 20 caracteres no vacía.
    - *Primer apellido*: una cadena de hasta 20 caracteres.
    - *Segundo apellido*: una cadena de hasta 20 caracteres.
    - *Contraseña*: una cadena alfanumérica de hasta 20 elementos.
*** RD28-Datos usuario a eliminar:
    - *Identificador de usuario*: un número entero.

*** RD29-Datos nueva comida:
    - *Identificador de usuario*: un número entero.
    - *Identificador de receta*: un número entero.
    - *Fecha*: tres conjuntos de enteros formados los dos primeros por conjuntos de dos cifras y el 		tercero por un conjunto de cuatro cifras, separados por barras ('/').

*** RD30-Datos comida:
    - *Identificador de usuario*: un número entero.
    - *Identificador de receta*: un número entero.
    - *Fecha*: tres conjuntos de enteros formados los dos primeros por conjuntos de dos cifras y el 		tercero por un conjunto de cuatro cifras, separados por barras ('/').

*** RD31-Identificador propietario de stock:
    - *Identificador de usuario*: un número entero.

*** RD32-Lista de stock:
    - *Identificador de producto*: un número entero.
    - *Nombre*: una cadena de hasta 20 caracteres no vacía.
    - *Calorías*: un número decimal positivo.
    - *Descripción*: una cadena de hasta 200 caracteres.
    - *Cantidad*: un número entero mayor que cero.

*** RD33-Identificador usuario para gasto diario:
    - *Identificador de usuario*: un número entero.

*** RD34-Valor de gasto diario:
    - *Gasto*: un número decimal.

*** RD35-Identificador usuario para gasto mensual:
    - *Identificador de usuario*: un número entero.

*** RD36-Valor de gasto mensual:
    - *Gasto*: un número decimal.

*** RD37-Usuario que consulta recetas disponibles:
    - *Identificador de usuario*: un número entero.

*** RD38-Lista recetas disponibles:
    - *Identificador de receta*: un número entero.
    - *Nombre*: una cadena de hasta 20 caracteres no vacía.
    - *Personas*: un número entero mayor que cero.
    - *Tiempo*: un número entero mayor que cero.
    - *Descripción*: una cadena de hasta 200 caracteres.

*** RD39-Identificador de dieta a consultar:
    - *Identificador de dieta*: un número entero.

*** RD40-Coste por super:
    - *Identificador de super*: un número entero.
    - *Nombre*:  una cadena de hasta 20 caracteres no vacía.
    - *Dirección*:  una cadena de hasta 30 caracteres.
    - *Teléfono*: una cadena de hasta 9 caracteres numéricos.
    - *Página web*: una cadena de hasta 20 caracteres.
    - *Gasto*: un número decimal.

*** RD41-Datos de identificación:
    - *Nombre*: una cadena de hasta 20 caracteres no vacía.
    - *Contraseña*: una cadena alfanumérica de hasta 20 elementos no vacía.

*** RD42-Identificador creador de dieta:
    - *Identificador de usuario*: un número entero.

*** RD43-Identificador usuario:
    - *Identificador de usuario*: un número entero.
*** RD44-Lista de recetas de dieta:
    - *Identificador de receta*: un número entero.
    - *Nombre*: una cadena de hasta 20 caracteres.
    - *Personas*: un número entero.
    - *Tiempo*: un número entero.
    - *Descripción*: una cadena de hasta 200 caracteres.

*** RD45-Identificador creador de dietas:
    - *Identificador de usuario*: un número entero.

*** RD46-Lista de dietas:
    - *Identificador de dieta*: un número entero.
    - *Nombre*: una cadena de hasta 20 caracteres no vacía.
    - *Descripción*: una cadena de hasta 200 caracteres.

*** RD47-Identificador consultor de recetas:
    - *Identificador de usuario*: un número entero.

*** RD48-Lista de recetas:
    - *Identificador de receta*: un número entero.
    - *Nombre*: una cadena de hasta 20 caracteres.
    - *Personas*: un número entero.
    - *Tiempo*: un número entero.
    - *Descripción*: una cadena de hasta 200 caracteres.

*** RD49-Identificador usuario propio:
    - *Identificador de usuario*: un número entero.

*** RD50-Datos usuario propio:
    - *Nombre*: una cadena de hasta 20 caracteres.
    - *Primer apellido*: una cadena de hasta 20 caracteres.
    - *Segundo apellido*: una cadena de hasta 20 caracteres.
    - *Nombre de usuario*: una cadena de hasta 20 caracteres.
    - *Contraseña*: una cadena alfanumérica de hasta 20 elementos.

*** RD51-Identificador cocinero:
    - *Identificador de usuario*: un número entero.

*** RD52-Lista de comidas:
    - *Identificador de usuario*: un número entero.
    - *Identificador de receta*: un número entero.
    - *Fecha*: tres conjuntos de enteros formados los dos primeros por
      conjuntos de dos cifras y el tercero por un conjunto de cuatro
      cifras, separados por barras ('/').

*** RD53-Datos comida a eliminar:
    - *Identificador de usuario*: un número entero.
    - *Identificador de receta*: un número entero.
    - *Fecha*: tres conjuntos de enteros formados los dos primeros por
      conjuntos de dos cifras y el tercero por un conjunto de cuatro
      cifras, separados por barras ('/').

** Requisitos funcionales
*** *RF1-Alta de un producto*
    Registra un producto en el sistema a partir de los datos de un producto proporcionados por un usuario.

*** *RF2-Modificar un producto*
    Modifica los datos de un producto almacenado en el sistema por los proporcionados por el usuario.

*** *RF3-Listar productos comprados*
    Devuelve los productos comprados por el usuario cuyo código se ha pasado como parámetro.

*** *RF4-Registrar un super*
    Añade un nuevo supermercado al sistema con la información facilitada por el usuario.

*** *RF5-Modificar un super*
    Altera la información de un supermercado registrado en el sistema por los nuevos datos suministrados.

*** *RF6-Nueva compra*
    Almacena una compra nueva en el sistema con la fecha actual y el identificador del usuario que la ha iniciado.

*** *RF7-Añadir producto a compra*
    Incluye una cantidad determinada de artículos identificados por los datos proporcionados por el usuario y su importe en euros.

*** *RF8-Eliminar producto de compra*
    Borra de una compra el producto adquirido en un supermercado  por el usuario.

*** *RF9-Añadir nueva dieta*
    Agrega una nueva dieta a las almacenadas en el sistema a partir de los datos dados por el usuario.

*** *RF10-Añadir receta a dieta*
    Incluye una receta en una dieta, ambas identificadas por los datos proporcionador por el usuario.

*** *RF11-Eliminar receta de dieta*
    Borra una receta de una dieta determinada, según los datos proporcionados por el usuario.

*** *RF12-Añadir nueva receta*
    Registra una receta en el sistema partiendo de los datos de una receta proporcionados por un usuario.

*** *RF13-Añadir producto a receta*
    Registra un ingrediente, junto con su cantidad, en una receta almacenada en el sistema, a partir de los datos introducidos por el usuario.

*** *RF14-Eliminar producto de receta*
    Elimina el producto identificado por el usuario de la receta proporcionada por el mismo.

*** *RF15-Modificar una receta*
    Altera la información de una receta registrada en el sistema por los nuevos datos que el usuario proporcione.

*** *RF16-Dar de alta un usuario*
    Registra un usuario nuevo en el sistema a partir de la información proporcionada por un usuario anónimo.

*** *RF17-Modificar un usuario*
    Modifica los datos de un usuario registrado en el sistema e identificado por los nuevos valores suministrados.

*** *RF18-Elimina un usuario*
    Suprime los datos de un usuario registrado en el sistema e identificado por los nuevos valores suministrados.

*** *RF19-Hacer comida*
    Registra la elaboración de una receta llevada a cabo por un usuario del sistema en la fecha actual.

*** *RF20-Listar stock*
    Muestra la cantidad de productos disponibles para un usuario.

*** *RF21-Calcular gasto diario*
    Devuelve el promedio de euros que gasta el usuario cada día en comidas.

*** *RF22-Calcular gasto mensual*
    Retorna la cantidad de euros que el usuario ha gastado este mes entre las comidas realizadas.

*** *RF23-Mostrar recetas disponibles*
    Devuelve una lista con todas las recetas que, según los ingredientes disponibles y las dietas que sigue, se pueden cocinar.

*** *RF24-Calcular precio de una dieta*
    Devuelve el coste de llevar a cabo cada receta de una dieta para cada supermercado.

*** *RF25-Identificar usuario*
    Comprueba si los datos proporcionados por el usuarios anónimo coinciden con los de algún usuario registrado en el sistema y devuelve su clave.

*** *RF26-Listar dieta completa*
    Muestra toda la información de las recetas asociadas a una dieta.

*** *RF27-Listar dietas*
    Recoge del sistema todas las dietas asociadas al usuario y los devuelve en una lista.

*** *RF28-Listar recetas*
    Devuelve una lista con todas las recetas del sistema, tanto las que pertenecen a alguna de nuestras dietas como las que no.

*** *RF29-Mostrar datos usuario*
    Muestra los campos registrados asociados al identificador de usuario.

*** *RF30-Listar comidas*
    Lista todos los platos que ha llevado a cabo el usuario del sistema.

*** *RF31-Eliminar comida*
    Borra una comida registrada a partir de la receta y el identificador de usuario registrado.

** *Validación cruzada de requisitos*
#+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./refinamientos/tablaRF1.png}
         \caption{Requisitos funcionales}
         \label{fig:Requisitos funcionales}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

#+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./refinamientos/tablaRF2.png}
         \caption{Requisitos funcionales}
         \label{fig:Requisitos funcionales}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX


** Restricciones semánticas
*** RS1
    No se pueden registrar usuarios con username repetidos.
*** RS2
    Todas las dietas deben estar asociadas a un usuario registrado.

* Esquema caja negra
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=1\linewidth]{./refinamientos/cajanegra.png}
         \caption{Caja Negra}
         \label{fig:Caja Negra}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

* Refinamiento 0
** DFD 0 (Esquema Armazón)
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=1\linewidth]{./refinamientos/dfd0.png}
         \caption{Esquema armazón}
         \label{fig:Esquema armazón}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

** Esquema externo 0
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=1\linewidth]{./refinamientos/externo0.png}
         \caption{Externo 0}
         \label{fig:Externo 0}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

** Entidad Relación 0
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.6\linewidth]{./refinamientos/er0.png}
         \caption{Entidad relación 0}
         \label{fig:Entidad relación 0}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

* Refinamiento 1
** DFD 1
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=1\linewidth]{./refinamientos/dfd1.png}
         \caption{Diagrama de flujo de datos 1}
         \label{fig:Diagrama de flujo de datos 1}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

** Esquema externo 1
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=1\linewidth]{./refinamientos/externo1.png}
         \caption{Externo 1}
         \label{fig:Externo 1}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

** Entidad Relación 1
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.7\linewidth]{./refinamientos/er1.png}
         \caption{Entidad relación 1}
         \label{fig:Entidad relación 1}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

* Refinamiento 2
** DFD 2 (Esquema Armazón)
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=1\linewidth]{./refinamientos/dfd2.png}
         \caption{Diagrama de flujo de datos 2}
         \label{fig:Diagrama de flujo de datos 2}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

** Esquema externo 2
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=1\linewidth]{./refinamientos/externo21.png}
         \caption{Externo 2.1}
         \label{fig:Externo 2.1}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=1\linewidth]{./refinamientos/externo22.png}
         \caption{Externo 2.2}
         \label{fig:Externo 2.2}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

** Entidad Relación 2
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./refinamientos/er2.png}
         \caption{Entidad relación 2}
         \label{fig:Entidad relación 2}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

** Entidad Relación final (atributos)
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=1\linewidth]{./refinamientos/erfinal.png}
         \caption{Entidad relación final}
         \label{fig:Entidad relación final}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

* Esquemas de Operación y Navegación
** Proceso: Gestión Compras
*** Lista de operaciones:
    1. Listar el nombre, las calorías, la descripción, la cantidad, el precio de los productos, el nombre del supermercado y la fecha de las compras realizadas por un usuario a partir de su IDUsuario.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Compras/01_ope.png}
         \caption{Esquema Operación - 01}
         \label{fig:ope01}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Compras/01_nav.png}
         \caption{Esquema Navegación - 01}
         \label{fig:nave01}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    2. Insertar una nueva compra.
       NOTA: se inserta como Fecha un valor igual a la fecha actual de sistema.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.3\linewidth]{./operaciones/img/Compras/02_ope.png}
         \caption{Esquema Operación - 02}
         \label{fig:ope02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.4\linewidth]{./operaciones/img/Compras/02_nav.png}
         \caption{Esquema Navegación - 02}
         \label{fig:nave02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    3. Asociar una comprar a partir del IDUsuario del usuario y el IDCompra de la compra.
       - Esquema de operación:
       #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Compras/03_ope.png}
         \caption{Esquema Operación - 03}
         \label{fig:ope03}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Compras/03_nav.png}
         \caption{Esquema Navegación - 03}
         \label{fig:nave03}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    4. Insertar una nueva línea de compra a partir del IDCompra, IDProducto
       IDSuper, cantidad y precio.
       - Esquema de operación:
       #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Compras/04_ope.png}
         \caption{Esquema Operación - 04}
         \label{fig:ope04}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Compras/04_nav.png}
         \caption{Esquema Navegación - 04}
         \label{fig:nave04}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    5. Eliminar una línea de compra a partir del IDCompra, IDProducto e IDSuper.
       - Esquema de operación:
       #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Compras/05_ope.png}
         \caption{Esquema Operación - 05}
         \label{fig:ope05}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Compras/05_nav.png}
         \caption{Esquema Navegación - 05}
         \label{fig:nave05}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

** Proceso: Gestión Productos
*** Lista de operaciones
    1. Insertar un producto a partir del nombre, descripción y
       calorías.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.6\linewidth]{./operaciones/img/Productos/01_ope.png}
         \caption{Esquema Operación - 01}
         \label{fig:ope01}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.6\linewidth]{./operaciones/img/Productos/01_nav.png}
         \caption{Esquema Navegación - 01}
         \label{fig:nave01}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    2. Modificar un producto a partir del IDProducto, nombre,
       descripción y calorías.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.6\linewidth]{./operaciones/img/Productos/02_ope.png}
         \caption{Esquema Operación - 02}
         \label{fig:ope02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
       #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.6\linewidth]{./operaciones/img/Productos/02_nav.png}
         \caption{Esquema Navegación - 02}
         \label{fig:nave02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    3. Asociar un producto a un super a partir del IDProducto y el IDSuper.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Productos/03_ope.png}
         \caption{Esquema Operación - 03}
         \label{fig:ope03}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Productos/03_nav.png}
         \caption{Esquema Navegación - 03}
         \label{fig:nave02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

** Proceso: Gestión Supermercados
*** Lista de operaciones
    1. Insertar un supermercado a partir del nombre, dirección,
       teléfono y página web.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.5\linewidth]{./operaciones/img/Super/01_ope.png}
         \caption{Esquema Operación - 01}
         \label{fig:ope01}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.5\linewidth]{./operaciones/img/Super/01_nav.png}
         \caption{Esquema Navegación - 01}
         \label{fig:nave01}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    2. Modificar nombre, dirección, teléfono y página web de un
       supermercado a partir del IDSuper.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.6\linewidth]{./operaciones/img/Super/02_ope.png}
         \caption{Esquema Operación - 02}
         \label{fig:ope02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.6\linewidth]{./operaciones/img/Super/02_nav.png}
         \caption{Esquema Navegación - 02}
         \label{fig:nave02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

** Proceso: Gestión Recetas
*** Lista de operaciones
    1. Insertar una receta a partir del nombre, personas, tiempo y
       descripción.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.5\linewidth]{./operaciones/img/Recetas/01_ope.png}
         \caption{Esquema Operación - 01}
         \label{fig:ope01}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.5\linewidth]{./operaciones/img/Recetas/01_nav.png}
         \caption{Esquema Navegación - 01}
         \label{fig:nave01}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    2. Modificar nombre, personas, tiempo y descripción de una receta
       a partir del IDReceta.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.5\linewidth]{./operaciones/img/Recetas/02_ope.png}
         \caption{Esquema Operación - 02}
         \label{fig:ope02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
       #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.5\linewidth]{./operaciones/img/Recetas/02_nav.png}
         \caption{Esquema Navegación - 02}
         \label{fig:nave02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    3. Insertar una asociación de un producto a partir de su
       IDProducto y una receta a partir de su IDReceta con una
       cantidad.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Recetas/03_ope.png}
         \caption{Esquema Operación - 03}
         \label{fig:ope03}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Recetas/03_nav.png}
         \caption{Esquema Navegación - 03}
         \label{fig:nave03}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    4. Eliminar asociación de un producto a partir de su IDProducto de
       una receta identificada por IDReceta.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Recetas/04_ope.png}
         \caption{Esquema Operación - 04}
         \label{fig:ope04}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Recetas/04_nav.png}
         \caption{Esquema Navegación - 04}
         \label{fig:nave04}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    5. Listar nombre, calorías, cantidad y descripción de los productos que
       componen una receta a partir de su IDReceta.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Recetas/05_ope.png}
         \caption{Esquema Operación - 05}
         \label{fig:ope05}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Recetas/05_nav.png}
         \caption{Esquema Navegación - 05}
         \label{fig:nave05}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

** Proceso: Gestión Dietas
*** Lista de operaciones
    1. Insertar una nueva dieta a partir de su nombre y
       descripción.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.5\linewidth]{./operaciones/img/Dietas/01_ope.png}
         \caption{Esquema Operación - 01}
         \label{fig:ope01}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
       #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.5\linewidth]{./operaciones/img/Dietas/01_nav.png}
         \caption{Esquema Navegación - 01}
         \label{fig:nave01}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    2. Insertar una asociación de una receta a partir de su IDReceta a
       una dieta identificada por su IDDieta.
       - Esquema de operación:
       #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Dietas/02_ope.png}
         \caption{Esquema Operación - 02}
         \label{fig:ope02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
       #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Dietas/02_nav.png}
         \caption{Esquema Navegación - 02}
         \label{fig:nave02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    3. Eliminar asociación de una receta a partir de su IDReceta de
       una dieta identificada por IDDieta.
       - Esquema de operación:
       #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Dietas/03_ope.png}
         \caption{Esquema Operación - 03}
         \label{fig:ope03}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
       #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Dietas/03_nav.png}
         \caption{Esquema Navegación - 03}
         \label{fig:nave03}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    4. Listar nombre y descripción de las dietas de un usuario a
       partir de su IDUsuario.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Dietas/04_ope.png}
         \caption{Esquema Operación - 04}
         \label{fig:ope04}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Dietas/04_nav.png}
         \caption{Esquema Navegación - 04}
         \label{fig:nave04}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    5. Listar nombre, personas, tiempo y descripción de cada una de
       las recetas asociadas a una dieta a partir de su IDDieta.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Dietas/05_ope.png}
         \caption{Esquema Operación - 05}
         \label{fig:ope05}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Dietas/05_nav.png}
         \caption{Esquema Navegación - 05}
         \label{fig:nave05}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    6. Insertar una asociacion entre una dieta por su IDDieta con un usuario por su IDUsuario.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Dietas/06_ope.png}
         \caption{Esquema Operación - 06}
         \label{fig:ope06}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Dietas/06_nav.png}
         \caption{Esquema Navegación - 06}
         \label{fig:nave06}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

** Proceso: Gestión Estadísticas
*** Lista de operaciones
    1. Mostrar el gasto medio diario en las comidas realizadas por un
       usuario a partir de su IDUsuario. Para ello divide el resultado de las siguientes operaciones:
       1.1 Calcular el gasto total de todas las compras de un usuario dado por su IDUsuario.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Estadisticas/11_ope.png}
         \caption{Esquema Operación - 1.1}
         \label{fig:ope11}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Estadisticas/11_nav.png}
         \caption{Esquema Navegación - 1.1}
         \label{fig:nave11}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

       1.2 Calcular el número de comidas llevadas a cabo por un usuario dado por su IDUsuario.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.6\linewidth]{./operaciones/img/Estadisticas/12_ope.png}
         \caption{Esquema Operación - 1.2}
         \label{fig:ope12}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.6\linewidth]{./operaciones/img/Estadisticas/12_nav.png}
         \caption{Esquema Navegación - 1.2}
         \label{fig:nave12}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    2. Mostrar el gasto mensual actual de un usuario a partir de su
       IDUsuario. Para ello divide el resultado de las siguientes operaciones:
       2.1 Calcular el gastos desde principio de mes de un usuario dado por su IDUsuario.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Estadisticas/21_ope.png}
         \caption{Esquema Operación - 2.1}
         \label{fig:ope21}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Estadisticas/21_nav.png}
         \caption{Esquema Navegación - 2.1}
         \label{fig:nave21}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

       2.2 Calcular el número de comidas realizadas por un usuario dado por su IDUSuario desde principio de mes.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.7\linewidth]{./operaciones/img/Estadisticas/22_ope.png}
         \caption{Esquema Operación - 2.2}
         \label{fig:ope22}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.7\linewidth]{./operaciones/img/Estadisticas/22_nav.png}
         \caption{Esquema Navegación - 2.2}
         \label{fig:nave22}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    3. Mostrar el nombre, calorías, descripción y cantidad de los
       productos existentes en el stock de un usuario a partir de su
       IDUsuario. Para ello resta los resultados de las siguientes operaciones para cada IDProducto:
       3.1 Calcular la cantidad total comprada de un producto dado su IDProducto por un usuario dado su IDUsuario.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Estadisticas/31_ope.png}
         \caption{Esquema Operación - 3.1}
         \label{fig:ope31}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Estadisticas/31_nav.png}
         \caption{Esquema Navegación - 3.1}
         \label{fig:nave31}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

       3.2 Calcular la cantidad total gastada en comidas de un producto a partir de su IDProducto, por un usuario a partir de su IDUSuario.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Estadisticas/32_ope.png}
         \caption{Esquema Operación - 3.2}
         \label{fig:ope32}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Estadisticas/32_nav.png}
         \caption{Esquema Navegación - 3.2}
         \label{fig:nave32}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    4. Mostar nombre, calorías y descripción de las recetas para las
       que dispone los ingredientes necesarios un usuario a partir de
       su IDUsuario. Para ello resta al resultado de la operación 3 (la anterior) el resultado de la operación 5 de gestión de recetas, que lista sus productos.

    5. Mostrar el nombre de los supermercados y precio total de lo que
       costaría comprar los ingredientes necesarios para elaborar las
       recetas que componen una dieta a partir de su IDDieta. Para ello lista los productos de cada receta de la dieta (operaciones 5 de Recetas y Dietas respectivamente) y los múltiplica por el resultado de la siguiente función:
       5.1 Listar el IDProducto, el nombre del producto, el nombre del super y el precio medio de comprar ese producto en ese super (media de todos los precios/cantidad) para un usuario a partir de su IDUsuario.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Estadisticas/51_ope.png}
         \caption{Esquema Operación - 5.1}
         \label{fig:ope51}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Estadisticas/51_nav.png}
         \caption{Esquema Navegación - 5.1}
         \label{fig:nave51}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

** Proceso: Gestión Comidas
*** Lista de operaciones
    1. Insertar una nueva comida.
       NOTA: se inserta como Fecha un valor igual a la fecha actual de sistema.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.5\linewidth]{./operaciones/img/Comidas/01_ope.png}
         \caption{Esquema Operación - 01}
         \label{fig:ope01}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.5\linewidth]{./operaciones/img/Comidas/01_nav.png}
         \caption{Esquema Navegación - 01}
         \label{fig:nave01}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    2. Asociar una comida con un IDComida a un usuario con IDUsuario.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Comidas/02_ope.png}
         \caption{Esquema Operación - 02}
         \label{fig:ope02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Comidas/02_nav.png}
         \caption{Esquema Navegación - 02}
         \label{fig:nave02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    3. Asociar una comida con un IDComida a una receta con IDReceta.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Comidas/03_ope.png}
         \caption{Esquema Operación - 03}
         \label{fig:ope03}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Comidas/03_nav.png}
         \caption{Esquema Navegación - 03}
         \label{fig:nave03}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    4. Eliminar una asociación entre una comida con un IDComida y una receta con IDReceta.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Comidas/04_ope.png}
         \caption{Esquema Operación - 04}
         \label{fig:ope04}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Comidas/04_nav.png}
         \caption{Esquema Navegación - 04}
         \label{fig:nave04}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    5. Eliminar una asociación entre una comida a partir de su IDComida y un usuario a partir de su IDUsuario.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Comidas/05_ope.png}
         \caption{Esquema Operación - 05}
         \label{fig:ope05}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./operaciones/img/Comidas/05_nav.png}
         \caption{Esquema Navegación - 05}
         \label{fig:nave05}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

    6. Eliminar una comida a partir de su IDComida.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.5\linewidth]{./operaciones/img/Comidas/06_ope.png}
         \caption{Esquema Operación - 06}
         \label{fig:ope06}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.5\linewidth]{./operaciones/img/Comidas/06_nav.png}
         \caption{Esquema Navegación - 06}
         \label{fig:nave06}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

** Proceso: Gestión Usuarios
*** Lista de operaciones
   1. Insertar un usuario a partir de su nombre, apellido1, apellido2,
      username y password.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.4\linewidth]{./operaciones/img/Usuarios/01_ope.png}
         \caption{Esquema Operación - 01}
         \label{fig:ope01}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.4\linewidth]{./operaciones/img/Usuarios/01_nav.png}
         \caption{Esquema Navegación - 01}
         \label{fig:nave01}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

   2. Eliminar un usuario a partir de su IDUsuario.
      NOTA: Esta operación lanza las operaciones de borrado de comidas, compras y dietas.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.4\linewidth]{./operaciones/img/Usuarios/02_ope.png}
         \caption{Esquema Operación - 02}
         \label{fig:ope02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.4\linewidth]{./operaciones/img/Usuarios/02_nav.png}
         \caption{Esquema Navegación - 02}
         \label{fig:nave02}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

   3. Modificar el nombre, apellido1, apellido2, username y password
      de un usuario a partir de su IDUsuario.
       - Esquema de operación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.4\linewidth]{./operaciones/img/Usuarios/03_ope.png}
         \caption{Esquema Operación - 03}
         \label{fig:ope03}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX
       - Esquema de navegación:
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.4\linewidth]{./operaciones/img/Usuarios/03_nav.png}
         \caption{Esquema Navegación - 03}
         \label{fig:nave03}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

* Diseño relacional
** Diseño lógico relacional
         #+begin_LaTeX
         \begin{figure}[!htp]
         \centering
         \includegraphics[width=0.9\linewidth]{./refinamientos/logico.png}
         \caption{Diseño lógico - 01}
         \label{fig:DLR}
         \medskip
         \footnotesize
         {}
         \end{figure}
       #+end_LaTeX

* Manual de usuario
   1. En primer lugar es necesario configurar el acceso a una base de
      datos oracle, la definición de host, user y password se hace en
      el fichero *include/login.db*.
   2. En segundo lugar hay que crear la estructura de la base de datos
      para ello se incluyen ficheros *.sql*:
      - *tablas.sql*: Estructura de la base de datos.
      - *datos.sql*: Datos de prueba que pueblan las tablas de la base
        de datos.
      - *consultas.sql*: Funciones y procedimientos de los que hace
        uso la aplicación.
   3. En tercer lugar es necesario alojar el contenido de la
      aplicación en un servidor web (puede ser local).
   4. Por último para acceder a la aplicación existe un usuario
      *admin* con password *admin*.


   Una vez identificado en el sistema como un usuario registrado,
   estará disponible toda la funcionalidad de la aplicación accediendo
   a cada una de las operaciones de cada proceso desde el menú superior.
